name: Deploy Project 1

on: 
    push:
        branches:
            - main

permissions:
    id-token: write
    contents: read

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Debug OIDC claims
              uses: github/actions-oidc-debugger@main
              with:
                audience: sts.amazonaws.com

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                role-to-assume: arn:aws:iam::509399624719:role/clearpointtraining-github-actions-role
                aws-region: us-east-1

            - name: Login to Amazon ECR
              uses: aws-actions/amazon-ecr-login@v2

            - name: Show repository files
              run: ls -la

            - name: Show Docker version
              run: docker --version

            - name: Build Docker image
              run: docker build -t project1-website:v4 ./docker

            - name: Tag Docker image for ECR
              run: docker tag project1-website:v4 509399624719.dkr.ecr.us-east-1.amazonaws.com/project1-website:v4

            - name: Push Docker image to ECR
              run: docker push 509399624719.dkr.ecr.us-east-1.amazonaws.com/project1-website:v4

            - name: Deploy image to EC2
              run: |
                aws ssm send-command \
                  --instance-ids "i-051b95331db1365fe" \
                  --document-name "AWS-RunShellScript" \
                  --parameters 'commands=[
                    "aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 509399624719.dkr.ecr.us-east-1.amazonaws.com",
                    "sudo docker pull 509399624719.dkr.ecr.us-east-1.amazonaws.com/project1-website:v4",
                    "sudo docker rm -f webserver-v4 || true",
                    "sudo docker run -d --name webserver-v4 --restart unless-stopped -p 80:80 509399624719.dkr.ecr.us-east-1.amazonaws.com/project1-website:v4"
                ]'