name: Deploy Project 1

on: 
    push:
        branches:
            - main

permissions:
    id-token: write
    contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: project1-website
  IMAGE_TAG: ${{github.sha}}
  EC2_INSTANCE_ID: i-051b95331db1365fe

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                role-to-assume: arn:aws:iam::509399624719:role/clearpointtraining-cicd-role
                aws-region: ${{env.AWS_REGION}}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build Docker image
              run: docker build -t ${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}} ./docker

            - name: Tag Docker image for ECR
              run: docker tag ${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}} ${{steps.login-ecr.outputs.registry}} ${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}

            - name: Push Docker image to ECR
              run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

            - name: Deploy image to EC2
              run: |
                aws ssm send-command \
                --instance-ids "${{ env.EC2_INSTANCE_ID }}" \ 
                --document-name "AWS-RunShellScript" \
                --parameters 'commands=[
                  "aws ecr get-login-password --region ${{ env.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}",
                  "sudo docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}",
                  "sudo docker rm -f webserver || true",
                  "sudo docker run -d --name webserver --restart unless-stopped -p 80:80 ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
                ]'