name: OIDC Test

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    test-oidc:
        runs-on: ubuntu-latest

        steps:
            - name: Request GitHub OIDC token
              run: |
                    RESPONSE=$(curl -s \
                        -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                        "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")

                    TOKEN=$(echo "$RESPONSE" | jq -r '.value')

                    echo "OIDC_TOKEN=$TOKEN" >> "$GITHUB_ENV"

            - name: Call AWS STS directly
              run: |
                    aws sts assume-role-with-web-identity \
                     --role-arn arn:aws:iam::509399624719:role/clearpointtraining-cicd-role \
                     --role-session-name oidc-direct-test \
                     --web-identity-token "$OIDC_TOKEN" \
                    --duration-seconds 900