name: OIDC Test

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    test-oidc:
        runs-on: ubuntu-latest

        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                role-to-assume: arn:aws:iam::509399624719:role/clearpointtraining-cicd-role
                aws-region: us-east-1

            - name: Verify AWS Identity
              run: aws sts get-caller-identity